
-- MySQL Script generated by MySQL Workbench
-- Tue May  7 07:37:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS Kanepe;

USE Kanepe;

-- -----------------------------------------------------
-- Table Enderecos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Enderecos (
    idEnderecos BIGINT NOT NULL AUTO_INCREMENT,
    Cidade VARCHAR(100) NOT NULL,
    Rua VARCHAR(100) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    cep VARCHAR(10) NOT NULL,
    numero VARCHAR(5) NOT NULL UNIQUE,
    PRIMARY KEY (idEnderecos)
);

-- -----------------------------------------------------
-- Table Usuarios
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Usuarios (
    idUsuarios BIGINT NOT NULL AUTO_INCREMENT,
    cpf_Usuario VARCHAR(11) NOT NULL UNIQUE,
    nome_Usuario VARCHAR(100) NOT NULL,
    senha_Usuario VARCHAR(100) NOT NULL,
    email_Usuario VARCHAR(100) NOT NULL UNIQUE,
    telefone BIGINT UNIQUE,
    Enderecos_idEnderecos BIGINT NOT NULL,
    PRIMARY KEY (idUsuarios),
    FOREIGN KEY (Enderecos_idEnderecos) REFERENCES Enderecos (idEnderecos)
);

-- -----------------------------------------------------
-- Table Produtores
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Produtores (
    idProdutores BIGINT NOT NULL AUTO_INCREMENT,
    nomeNegocio VARCHAR(100) NOT NULL,
    Usuarios_idUsuarios BIGINT NOT NULL,
    Enderecos_idEnderecos BIGINT NOT NULL,
    cnpj VARCHAR(14) NOT NULL UNIQUE,
    PRIMARY KEY (idProdutores),
    FOREIGN KEY (Usuarios_idUsuarios) REFERENCES Usuarios (idUsuarios),
    FOREIGN KEY (Enderecos_idEnderecos) REFERENCES Enderecos (idEnderecos)
);

-- -----------------------------------------------------
-- Table Produtos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Produtos (
    idProdutos BIGINT NOT NULL AUTO_INCREMENT,
    produtoCod bigint not null,
    quantidade INT NOT NULL,
    validade DATE NOT NULL,
    nome_Produto VARCHAR(100) NOT NULL,
    preco DECIMAL(65) NOT NULL,
    Produtores_idProdutores BIGINT NOT NULL,
    PRIMARY KEY (idProdutos),
    FOREIGN KEY (Produtores_idProdutores) REFERENCES Produtores (idProdutores)
);

-- -----------------------------------------------------
-- Table Clientes
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Clientes (
    idClientes BIGINT NOT NULL AUTO_INCREMENT,
    Usuarios_idUsuarios BIGINT NOT NULL,
    Enderecos_idEnderecos BIGINT NOT NULL,
    PRIMARY KEY (idClientes),
    FOREIGN KEY (Usuarios_idUsuarios) REFERENCES Usuarios (idUsuarios),
    FOREIGN KEY (Enderecos_idEnderecos) REFERENCES Enderecos (idEnderecos)
);

-- -----------------------------------------------------
-- Table Vendas
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Vendas (
    idVendas BIGINT NOT NULL AUTO_INCREMENT,
    quantidade INT NOT NULL,
    Produtores_idProdutores BIGINT NOT NULL,
    Clientes_idClientes BIGINT NOT NULL,
    PRIMARY KEY (idVendas),
    FOREIGN KEY (Produtores_idProdutores) REFERENCES Produtores (idProdutores),
    FOREIGN KEY (Clientes_idClientes) REFERENCES Clientes (idClientes)
);

-- -----------------------------------------------------
-- Table Carrinho
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Carrinho (
    Vendas_idVendas BIGINT NOT NULL,
    Produtos_idProdutos BIGINT NOT NULL,
    idCarrinho BIGINT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (idCarrinho),
    FOREIGN KEY (Vendas_idVendas) REFERENCES Vendas (idVendas),
    FOREIGN KEY (Produtos_idProdutos) REFERENCES Produtos (idProdutos)
);
